CREATE TABLE SERVIDOR (
    ID_SERVIDOR VARCHAR(50) PRIMARY KEY,
    NOMBRE VARCHAR(50) NULL
);

CREATE TABLE CANAL (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SERVIDOR_ID VARCHAR(50) NOT NULL,
    TIPO_CANAL VARCHAR(50),
    ID_CANAL VARCHAR(50),

    FOREIGN KEY (SERVIDOR_ID) REFERENCES SERVIDOR(ID_SERVIDOR)
);



