CREATE TABLE SERVIDOR (
    ID VARCHAR(50) PRIMARY KEY,
    CODIGO_CANAL_AVISOS VARCHAR(50),
    FOREIGN KEY (CODIGO_CANAL_AVISOS) REFERENCES CANAL(ID)
);

CREATE TABLE CANAL (
    ID VARCHAR(50) PRIMARY KEY,
    SERVIDOR_ID VARCHAR(50),
    FOREIGN KEY (SERVIDOR_ID) REFERENCES SERVIDOR(ID)
);